[App.Job1]
AddressToListen = "0x18Df82C7E422A42D47345Ed86B0E935E9718eBda"
EventName = "NumberChanged(uint256)"

[App.Job2]
AddressToListen = "0x18Df82C7E422A42D47345Ed86B0E935E9718eBda"
EventName = "NumberChanged(uint256)"

[Eth]
EthHTTPURL = "http://localhost:8545"
EthWSURL = "ws://localhost:8546"
